'use client';

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { useBranding } from '@/lib/branding';

export default function PrivacyPage() {
  const branding = useBranding();

  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-[#8ea095] hover:text-white transition-colors mb-8">
        <ArrowLeft size={14} /> Back to home
      </Link>
      <h1 className="text-3xl font-semibold tracking-tight text-white mb-2">Privacy Policy</h1>
      <p className="text-sm text-[#5a6b62] mb-10">Last updated: {new Date().getFullYear()}</p>

      <div className="space-y-8 text-sm leading-relaxed text-[#c7d6cf]">
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">1. Information we collect</h2>
          <p>
            We collect the information you provide when creating an account (email, username) and
            data generated by using the platform (server configuration, files you upload, console
            activity, resource usage).
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">2. How we use it</h2>
          <p>
            Your information is used to operate your account, provision and run your servers, send
            transactional emails (verification, password resets, billing notices), and enforce plan
            limits.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">3. Data storage</h2>
          <p>
            Account and server metadata is stored in our PostgreSQL database. Server files live inside
            your server&rsquo;s isolated Docker container / mounted volume on our infrastructure.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">4. Third parties</h2>
          <p>
            We don&rsquo;t sell your data. Discord is used only if you choose to link it for support or
            purchases; email delivery uses an SMTP provider configured by the administrator.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">5. Your choices</h2>
          <p>
            You can update your account details, change your password, or delete your servers at any
            time from your dashboard. Contact support to request full account deletion.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">6. Contact</h2>
          <p>
            Questions about this policy? Reach out on{' '}
            {branding.discordInvite ? (
              <a href={branding.discordInvite} target="_blank" rel="noopener noreferrer" className="text-signal-500 hover:underline">
                Discord
              </a>
            ) : (
              'our support channel'
            )}
            {branding.supportEmail && (
              <>
                {' '}or email{' '}
                <a href={`mailto:${branding.supportEmail}`} className="text-signal-500 hover:underline">
                  {branding.supportEmail}
                </a>
              </>
            )}
            .
          </p>
        </section>
      </div>
    </main>
  );
}
